### ISSUE TITLE
 Incorrect name of materials

### ISSUE THREAD

**Issue by Dimak25** [QuestionableM/Blueprint-Converter#1]
When porting the model, it turns out that the name of the textures is random
example: b86bc11c-8922-47c2-b5bc-e184d3378a81 222222 0
when the actual naming is:blk_wornmetal_nor.TGA

![blender_J5e2xOzsB9](https://user-images.githubusercontent.com/93008578/138509278-ae7962a6-cfcf-4fe4-a765-5479fe33f451.png)

**Comment by QuestionableM** [comment]
It's not random. This naming scheme consists of 3 parts: UUID of the object, color and sub mesh index.

**Comment by Dimak25** [comment]
> Это не случайно. Эта схема именования состоит из 3 частей: UUID объекта, цвет и индекс подсети.

Then can you fix it?
